// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmnidfxwqseoynsflnqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtbmlkZnh3cXNlb3luc2ZsbnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDE4MzgsImV4cCI6MjA2ODg3NzgzOH0.QLaYxhKR03y_syJDvSPbZHHpuVNlnk7aXdwGklsS3nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});